eypstats/urls.py
from django.conf import settings
from django.urls import include, re_path
from statisticscore.admin import admin_site

urlpatterns = [
    re_path(r'^', include('statisticscore.urls')),
    re_path(r'^admin/', admin_site.urls),
]

handler404 = 'statisticscore.views.public_views.handler404'
handler500 = 'statisticscore.views.public_views.handler500'

statisticscore/urls.py
from django.urls import re_path
from django.conf.urls.static import static
from django.conf import settings

from statisticscore.views import *
from statisticscore.url_patterns.api import api_urls
from statisticscore.url_patterns.session import session_urls

# The URLs are quite important to the GA Stats system, as there's a custom API and system for accessing various forms
# Sessions, Debates, Point Submit and Vote Submit pages are accessed using the id's of the session/committee.
# The special ones are the api urls that the debate and session pages use for the live reloading to function,
# they're linked to custom views that output some pretty JSON output.

app_name = 'statisticscore'

urlpatterns = [
    re_path(r'^$', home, name='home'),
    re_path(r'^login/$', ga_login, name='login'),
    re_path(r'^logout/$', ga_logout, name='logout'),
    re_path(r'^get_started/$', get_started, name='get_started'),
    re_path(r'^changelog/$', changelog, name='changelog'),
    re_path(r'^create_session/$', create_session, name='create_session'),
    re_path(r'^highscores/$', high_scores, name='high_scores'),
    re_path(r'^topics/$', FilteredTopicsListView.as_view(), name='topics'),
    # path('topics/<int:pk>/edit', TopicUpdate.as_view(), name='update_topic'),
    # path('topics/<int:pk>/', TopicDetail.as_view(), name='topic_detail'),
    re_path(r'^overview/(?P<session_id>[0-9]+)/$', overview, name='overview'),
    re_path(r'^edit/(?P<session_id>[0-9]+)/$', edit, name='edit'),
    re_path(r'^committees/(?P<session_id>[0-9]+)/$', create_committee, name='create_committee'),
    re_path(r'^manage/(?P<session_id>[0-9]+)/$', manage, name='manage'),
    re_path(r'^gender/(?P<session_id>[0-9]+)/$', gender, name='gender'),
    re_path(r'^runningorder/(?P<session_id>[0-9]+)/$', runningorder, name='runningorder'),
]

urlpatterns += api_urls
urlpatterns += session_urls

if settings.IS_DEVELOPMENT:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

statisticscore/forms/active.py
from django import forms


class ActiveDebateForm(forms.Form):
    #The Active Debate form is another more complex one, as it requires an array of the avaliable debates to chose from.
    #This is set up in the same way as the Point form, with a custom extra argument.
    def __init__(self, active_debate_choices, *args, **kwargs):
        super(ActiveDebateForm, self).__init__(*args, **kwargs)
        self.fields['active_debate'].choices = active_debate_choices

    #This is the same as the point form, the same normal data with an empty choices argument.
    session = forms.CharField(max_length=100, required=True)
    active_debate = forms.ChoiceField(choices=(), required=True)

class ActiveRoundForm(forms.Form):
    #Same as the Active Debate form, a custom argument for the rounds. There can't just be a maximum round number,
    #there has to be an array with the name (number) of each round.
    def __init__(self, active_round_choices, *args, **kwargs):
        super(ActiveRoundForm, self).__init__(*args, **kwargs)
        self.fields['active_round'].choices = active_round_choices

    #Setting up arguments again.
    session = forms.CharField(max_length=100, required=True)
    active_round = forms.ChoiceField(choices=(), required=True)

statisticscore/forms/committee.py
from django import forms


class CommitteeForm(forms.Form):
    pk = forms.IntegerField(required=False)
    name = forms.CharField(max_length=8)
    topic = forms.CharField(max_length=1000)

statisticscore/forms/content.py
from django import forms


class ContentForm(forms.Form):
    #The contentpoint form needs special point types, but except for that it's a pretty simple form.
    POINT = 'P'
    DIRECT_RESPONSE = 'DR'
    POINT_TYPES = (
        (POINT, 'Point'),
        (DIRECT_RESPONSE, 'Direct Response'),
    )

    session = forms.CharField(max_length=100, required=True)
    committee = forms.CharField(max_length=8, required=True)
    debate = forms.CharField(max_length=8, required=True)
    point_type = forms.ChoiceField(choices=POINT_TYPES, required=True)
    content = forms.CharField(required=True)

class ContentEditForm(forms.Form):
    #The contentpoint form needs special point types, but except for that it's a pretty simple form.
    POINT = 'P'
    DIRECT_RESPONSE = 'DR'
    POINT_TYPES = (
        (POINT, 'Point'),
        (DIRECT_RESPONSE, 'Direct Response'),
    )

    pk = forms.IntegerField(min_value=0, required=True)
    session = forms.IntegerField(min_value=0, required=True)
    committee = forms.CharField(max_length=8, required=True)
    debate = forms.CharField(max_length=8, required=True)
    point_type = forms.ChoiceField(choices=POINT_TYPES, required=True)
    content = forms.CharField(required=True)

statisticscore/forms/delete.py
from django import forms

class DeleteDataForm(forms.Form):
    pk = forms.IntegerField(min_value=0, required=True)

statisticscore/forms/login.py
from django import forms
from django.contrib.auth import get_user_model


class LoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))

User = get_user_model()

statistics/views.py
import time
import json

from datetime import date
from datetime import datetime
from time import strftime

from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.models import User
from django.contrib.auth.models import Group
from django.contrib.auth import get_user_model, authenticate, login, logout
from django.contrib import messages

#Importing all models for statistics.
from .models import Session, Committee, Point, ContentPoint, Vote, SubTopic, ActiveDebate, ActiveRound

#Importing the forms too.
from .forms import SessionForm,  SessionEditForm, PointForm, VoteForm, ContentForm, JointForm, ActiveDebateForm, ActiveRoundForm, LoginForm

def home(request):
    #All the home page needs is a list of all sessions ordered by the start date. We create the list, then the context and finally render the template.
    latest_sessions_list = Session.objects.filter(session_is_visible=True).order_by('-session_start_date')[:20]
    context = {'latest_sessions_list': latest_sessions_list}
    return render(request, 'statistics/home.html', context)

def ga_login(request):
# This view is shown, when a user tries to view the submit form, but isn't logged in. After they log in, they'll be taken to /submit/.
    form = LoginForm(request.POST or None)

    if form.is_valid():
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        print username, password

        user = authenticate(username=username,
                            password=password)

        if user is not None:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect('/')
            else:
                return HttpResponseRedirect('/login')
        else:
            return HttpResponseRedirect('/login')

    template = 'statistics/login.html'
    context = {'form': form}
    return render(request, template, context)


def ga_logout(request):
    # If the user visits /logout/ he will be logged out.

    logout(request)
    return HttpResponseRedirect('/')


def create_session(request):
    #If the user is trying to create a session
    if request.method == 'POST':
        print request.POST
        #Fill an instance of a SessionForm with the request data.
        form = SessionForm(request.POST)

        if form.is_valid():
            print 'is valid'
            #We need to set up time varaibles for the start and end of sessions.
            #We do this by creating date objects and combining the date objects with time midnight
            t_start = form.cleaned_data['start_date']
            t_end = form.cleaned_data['end_date']
            start_date = datetime.combine(t_start, datetime.min.time())
            end_date = datetime.combine(t_end, datetime.min.time())

            #We need to turn the voting 'True' and 'False' strings into actual booleans.
            if form.cleaned_data['voting'] == 'True':
                voting = True
            else:
                voting = False

            #Creating a lowercase string with no spaces from the session name to use for usernames
            name = ''.join(form.cleaned_data['name'].split()).lower()

            #Creating the Admin user
            admin_user = User.objects.create_user(username = name + '_admin',
                email = form.cleaned_data['email'],
                password = form.cleaned_data['admin_password'])

            #Adding the admin user to the admin group.
            admin_group = Group.objects.get(name='SessionAdmin')
            admin_group.user_set.add(admin_user)

            #Creating the Submit user
            submit_user = User.objects.create_user(username = name,
                email = form.cleaned_data['email'],
                password = form.cleaned_data['submit_password'])

            #Adding the Submit user to the submit group.
            submit_group = Group.objects.get(name='SessionSubmit')
            submit_group.user_set.add(submit_user)

            #We need to create a session, active debate and active round. We also need to create 2 new users for the session.
            session = Session(session_name = form.cleaned_data['name'],
                session_description = form.cleaned_data['description'],
                session_picture = form.cleaned_data['picture'],
                session_email = form.cleaned_data['email'],
                session_country = form.cleaned_data['country'],
                session_start_date = start_date,
                session_end_date = end_date,
                session_statistics = form.cleaned_data['statistics'],
                session_color = form.cleaned_data['color'],
                session_rounds_enabled = True,
                session_subtopics_enabled = True,
                session_is_visible = False,
                session_voting_enabled = voting,
                session_max_rounds = form.cleaned_data['max_rounds'],
                session_admin_user = admin_user,
                session_submission_user = submit_user,
                )
            session.save()
            active_debate = ActiveDebate(session = session, active_debate = '')
            active_debate.save()
            active_round = ActiveRound(session = session, active_round = 1)
            active_round.save()

            #Once we've done all that, lets say thanks for all that hard work.
            return HttpResponseRedirect('/welcome/' + str(session.pk) + '/')
        else:
            print 'Wasnt valid'
            print form.errors
    else:
        #Otherwise, create a nice new form for the user.
        form = SessionForm()

    context = {'form': form}
    return render(request, 'statistics/session_create.html', context)

def welcome(request, session_id):
    session = Session.objects.get(pk=session_id)
    committees = Committee.objects.filter(session=session).order_by('committee_name')
    context = {'session': session, 'committees': committees}
    return render(request, 'statistics/welcome.html', context)

def edit(request, session_id):
    s = Session.objects.get(pk=session_id)
    # If the User is trying to edit the session
    if request.method == 'POST':
        #Fill an instance of the form with the request data.
        form = SessionEditForm(request.POST)
        #Check if the created form is a valid form.
        if form.is_valid():
            print 'is valid'
            #We need to set up time varaibles for the start and end of sessions.
            #We do this by creating date objects and combining the date objects with time midnight
            t_start = form.cleaned_data['start_date']
            t_end = form.cleaned_data['end_date']
            start_date = datetime.combine(t_start, datetime.min.time())
            end_date = datetime.combine(t_end, datetime.min.time())

            s.session_name = form.cleaned_data['name']
            s.session_description = form.cleaned_data['description']
            s.session_picture = form.cleaned_data['picture']
            s.session_email = form.cleaned_data['email']
            s.session_country = form.cleaned_data['country']
            s.session_start_date = start_date
            s.session_end_date = end_date
            s.session_statistics = form.cleaned_data['statistics']
            s.session_voting_enabled = form.cleaned_data['voting']
            s.session_max_rounds = form.cleaned_data['max_rounds']
            s.session_color = form.cleaned_data['color']
            s.session_is_visible = form.cleaned_data['is_visible']
            #Save the newly edited session
            s.save()

            messages.add_message(request, messages.SUCCESS, 'Session Updated')

    else:
        form = SessionEditForm({'name': s.session_name,
            'description': s.session_description,
            'email': s.session_email,
            'country': s.session_country,
            'picture': s.session_picture,
            'start_date': s.session_start_date.strftime("%Y-%m-%d"),
            'end_date': s.session_end_date.strftime("%Y-%m-%d"),
            'statistics': s.session_statistics,
            'voting': s.session_voting_enabled,
            'max_rounds': s.session_max_rounds,
            'color': s.session_color,
            'is_visible': s.session_is_visible})

    context = {'session': s, 'form': form}
    return render(request, 'statistics/session_edit.html', context)


def add(request, session_id):
    pass

def session(request, session_id):
    #The Session page uses static content and content that is constantly updated, the satic content is loaded with the view
    #and the updating content updates with the session api, defined further down.

    #The static data here is simply a list of the available committees (we can assume those don't change during live statistics)
    #and the name and data of the session itself.
    session_committee_list = Committee.objects.filter(session__id=session_id)[:30]
    session = Session.objects.get(pk=session_id)
    voting_enabled = session.session_voting_enabled
    context = {'session_committee_list': session_committee_list, 'session_id': session_id, 'session': session, 'voting_enabled': voting_enabled}
    return render(request, 'statistics/session.html', context)

def debate(request, session_id, committee_id):
    #Same for debates as for sessions, the only static content is the name and data of the committee and the session.
    #The rest of the point/voting data comes through the api that can constantly be updated.
    c = Committee.objects.get(pk=committee_id)
    s = Session.objects.get(pk=session_id)
    #The statistics_type will let us render different templates based on the statistics selected by the user.
    statistics_type = s.session_statistics
    print statistics_type

    #The voting enabled option lets us change the html content and js so that the voting is not displayed.
    voting_enabled = s.session_voting_enabled

statisticscore/views/helpers.py
from raven import Client
from django.conf import settings
from django.shortcuts import render
from django.urls import reverse
from django.contrib import messages
from django.http import HttpResponseRedirect


raven_client = Client(settings.RAVEN_CONFIG['dsn'])


# This is a central function. It replaces 'render' in cases where the user has to be authorized to view the page, not just authenticated.
def check_authorization_and_render(request, template, context, session, admin_only=True):
    if admin_only:  # This also refers to the session admin user AND any superuser
        if request.user == session.admin_user or request.user.is_superuser:
            return render(request, template, context)
        else:
            messages.add_message(request, messages.ERROR,
                                 'You are not authorized to view this page. You need to log in as the ' + session.name + ' admin.')
            return HttpResponseRedirect(reverse('statisticscore:login'))
    else:
        if request.user == session.admin_user or request.user == session.submission_user or request.user.is_superuser:
            return render(request, template, context)
        else:
            messages.add_message(request, messages.ERROR,
                                 'You are not authorized to view this page. You need to log in as a ' + session.name + ' user.')
            return HttpResponseRedirect(reverse('statisticscore:login'))

statisticscore/views/public_views.py
from django.shortcuts import render

def committee(request, session_id, committee_id):
    # The idea is not only to have a "debate page", where you can see how many points are made during the debate of a particular resolution,
    # but also for there to be a "committee page", where delegates can see how many points their
    # committee has made during each debate, what was the longest time between points etc.
    # This should be made in due time.
    pass


def handler404(request, exception):
    return render(request, 'statisticscore/404.html')


def handler500(request):
    return render(request, 'statisticscore/500.html')

statisticscore/templates/statisticscore/base.html
<!doctype html>
<html class="no-js" lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

        <title>{% block page_title %}{% endblock %} | GA Statistics</title>

        <meta name="description" content="GA Statistics is a project of the European Youth Parliament that gathers statistics about General Assemblies around Europe.">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="theme-color" content="#2E4496"> <!-- This line colours the navigation bar in Chrome Mobile with the given hex code. -->

        {% load static %}

        <link rel="apple-touch-icon" href="{% static 'statisticscore/images/apple-touch-icon.png' %}" />
        <link rel="icon" href="{% static 'statisticscore/images/apple-touch-icon.png' %}" />
        <link rel="stylesheet" href="{% static 'statisticscore/css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'statisticscore/css/material-stats.css' %}">
        <link rel="stylesheet" href="{% static 'statisticscore/css/ripples.min.css' %}">
        <link rel="stylesheet" href="{% static 'statisticscore/css/datetimepicker.css' %}">
        <link rel="stylesheet" href="{% static 'statisticscore/css/main.min.css' %}">

        <script src="{% static 'statisticscore/js/modernizr-2.8.3-respond-1.4.2.min.js' %}"></script>

        <!-- The custom fonts are loaded at the bottom of the page to improve performance. -->

    </head>
    <body>


        {% include "statisticscore/navbar.html" %}

        {% block jumbotron %}
        {% endblock %}

        <!--[if lt IE 8]>
          <div class="container">
            <div class="alert alert-dismissable alert-danger shadow-z-2">
              <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
            </div>
          </div>
        <![endif]-->


    <div class="container">

      {% if messages %}
        <div class="message">
          <br>
          {% for message in messages %}
            <div class="alert alert-dismissable alert-success shadow-z-2">
              <p {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</p>
            </div>
          {% endfor %}
          <script type="text/javascript">
              window.setTimeout(function () {
                  $(".message").fadeTo(500, 0).slideUp(500, function () {
                      $(this).remove();
                  });
              }, 5000);
          </script>
        </div> <!-- /message -->
      {% endif %}


      {% block content %}
      {% endblock %}

      {% if not no_footer %}
      <hr>
      <footer>
        <p style="float: left; width: 33%; text-align: left;">&copy; European Youth Parliament {% now "Y" %}</p>
        <p style="float: left; width: 33%; text-align: center;">Made by Oliver Stenbom and Athena Wolfskämpf</p>
        <p style="float: left; width: 33%; text-align: end;"><a target="_blank" href="https://github.com/eyp-developers/statistics/issues">Bugs and Feature Requests</a> | <a href="{% url 'statisticscore:changelog' %}">Changelog</a></p>
      </footer>
      {% endif %}
    </div> <!-- /container -->

        <script src="{% static 'statisticscore/js/jquery-1.11.2.min.js' %}"></script>
        <script src="{% static 'statisticscore/js/highcharts.js' %}"></script>
        <script src="{% static 'statisticscore/js/bootstrap.min.js' %}"></script>
        <script src="{% static 'statisticscore/js/moment.min.js' %}"></script>
        <script src="{% static 'statisticscore/js/material.js' %}"></script>
        <script src="{% static 'statisticscore/js/datetimepicker.js' %}"></script>
        <script src="{% static 'statisticscore/js/ripples.min.js' %}"></script>
        <script src="{% static 'statisticscore/js/masonry.min.js' %}"></script>

        {% block footer_scripts %}
        {% endblock %}

        <script>
          $.material.init()
        </script>


    </body>
    <link href='https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,200italic,300,300italic,200,400italic,600,600italic,700,700italic,900,900italic&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
</html>

statisticscore/templates/statisticscore/overview.html
{% extends 'statisticscore/base.html' %}

{% load static %}

{% block page_title %}Welcome - {{ session.name }}{% endblock %}

{% block jumbotron %}
    <div class="welcome-jumbo jumbotron">
        <div class="container">
            <h1>Welcome to GA Statistics, {{ session.name }}</h1>
            <p>Congratulations on creating your GA Statistics Session! There are a few more things you need to do before you're ready to go.</p>
        </div><!--/.container -->
    </div><!--/.jumbotron -->
{% endblock %}

{% block content %}

    {% if not session.is_visible %}
        <div class="alert alert-dismissable alert-warning">
            <button type="button" class="close" data-dismiss="alert">×</button>
            Your session isn't visible to the public yet. After you have added all your committees, change the visibility setting here: <a href="{% url 'statisticscore:edit' session.pk %}">{% url 'statisticscore:edit' session.pk %}</a>
        </div>
    {% endif %}
    <div class="alert alert-dismissable alert-info">
        <button type="button" class="close" data-dismiss="alert">×</button>
        This is really important stuff to know, but don't worry, you can always come back here with this url: <a href="{% url 'statisticscore:overview' session.pk %}">{% url 'statisticscore:overview' session.pk %}</a>
    </div>

    <div class="panel panel-primary">
        <div class="panel-heading">
            <h3 class="panel-title">Usernames</h3>
        </div>
        <div class="panel-body">
            <h4>Your Admin Username is <b>{{ session.admin_user }}</b><h4>
                <h5>The Admin Password that you entered when you signed up.</h5>
                <br>
                <h4>Your Submission Username is <b>{{ session.submission_user }}</b></h4>
                <h5>The Submission Password that you entered when you signed up.</h5>
        </div>
    </div>
    <div class="panel panel-primary">
        <div class="panel-heading">
            <h3 class="panel-title">{{ session.name }} Links</h3>
        </div>
        <div class="panel-body">
            <h2>Your Session ID is <b>{{ session.pk }}</b></h2>
            <p>You can use your session ID for all kinds of things (some only if you're logged in as an admin).</p>

            <h3>You can add your committees:</h3>
            <h4><a href="{% url 'statisticscore:create_committee' session.pk %}">{% url 'statisticscore:create_committee' session.pk %}</a> - This is where you add all your committees and subtopics.</h3>

                <h3>You can edit the session you just made:</h3>
                <h4><a href="{% url 'statisticscore:edit' session.pk %}">{% url 'statisticscore:edit' session.pk %}</a> - This is where you can change things like the maximum amount of rounds you'll have.</h3>

                    <h3>You can manage your session:</h3>
                    <h4><a href="{% url 'statisticscore:manage' session.pk %}">{% url 'statisticscore:manage' session.pk %}</a> - This is where you let the system know which debate and round is going on at the moment.</h3>
                        <p>It's also where you can edit recent points, contentpoints and votes</p>

                        {% if session.gender_enabled %}
                            <h3>You can track the equality of your session:</h3>
                            <h4><a href="{% url 'statisticscore:gender' session.pk %}">{% url 'statisticscore:gender' session.pk %}</a> - This is where you add "Gender Points" which only show up in the admin.</h3>
                        {% endif %}

        </div>
    </div>
    <div class="panel panel-primary">
        <div class="panel-heading">
            <h3 class="panel-title">Committees</h3>
        </div>
        <div class="panel-body">
            {% if committees %}
                <table class="table table-striped table-hover ">
                    <thead>
                    <tr>
                        <th>ID</th>
                        <th>Name</th>
                        <th>Debate URL</th>
                        {% if session.session_statistics == 'JF' %}
                            <th>Joint Form URL</th>
                        {% elif session.session_statistics == 'SF' %}
                            <th>Statistics Form URL</th>
                            <th>Content Form URL</th>
                        {% elif session.session_statistics == 'C' %}
                            <th>Content Form URL</th>
                        {% elif session.session_statistics == 'S' %}
                            <th>Statistics Form URL</th>
                        {% elif session.session_statistics == 'R' or session.session_statistics == 'RC' %}
                            <th>Running Order URL</th>
                        {% endif %}
                        {% if session.voting_enabled %}
                            <th>Voting URL<th>
                        {% endif %}
                    </tr>
                    </thead>
                    <tbody>
                    {% for committee in committees %}
                        <tr>
                            <td>{{ committee.pk }}</td>
                            <td>{{ committee.name }}
                            <td><a href="{% url 'statisticscore:debate' session.pk committee.pk %}">{% url 'statisticscore:debate' session.pk committee.pk %}</a></td>
                            {% if session.session_statistics == 'JF' %}
                                <td><a href="{% url 'statisticscore:joint' session.pk committee.pk %}">{% url 'statisticscore:joint' session.pk committee.pk %}</a></td>
                            {% elif session.session_statistics == 'SF' %}
                                <td><a href="{% url 'statisticscore:point' session.pk committee.pk %}">{% url 'statisticscore:point' session.pk committee.pk %}</a></td>
                                <td><a href="{% url 'statisticscore:content' session.pk committee.pk %}">{% url 'statisticscore:content' session.pk committee.pk %}</a></td>
                            {% elif session.session_statistics == 'C' %}
                                <td><a href="{% url 'statisticscore:content' session.pk committee.pk %}">{% url 'statisticscore:content' session.pk committee.pk %}</a></td>
                            {% elif session.session_statistics == 'S' %}
                                <td><a href="{% url 'statisticscore:point' session.pk committee.pk %}">{% url 'statisticscore:point' session.pk committee.pk %}</a></td>
                            {% elif session.session_statistics == 'R' or session.session_statistics == 'RC' %}
                                <td><a href="{% url 'statisticscore:predict' session.pk committee.pk %}">{% url 'statisticscore:predict' session.pk committee.pk %}</a></td>
                            {% endif %}
                            {% if session.voting_enabled %}
                                <td><a href="{% url 'statisticscore:vote' session.pk committee.pk %}">{% url 'statisticscore:vote' session.pk committee.pk %}</a><td>
                            {% endif %}
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
                <p>We highly recommend using the links above and giving them to your chairs/journos/orgas who will fill in data for one committee each. Using those links minimises the probability of something going wrong = less work for you.
                    However, if you only have one small group of people filling in all statistics, there are some special forms that can make their lives a little easier:</p>
                {% if session.session_statistics == 'JF' %}
                    <h5>Joint Form for any committee: <a href="{% url 'statisticscore:joint_all' session.pk %}">{% url 'statisticscore:joint_all' session.pk %}</a></h5>
                {% elif session.session_statistics == 'SF' %}
                    <h5>Statistics Form for any committee: <a href="{% url 'statisticscore:point_all' session.pk %}">{% url 'statisticscore:point_all' session.pk %}</a></h5>
                    <h5>Content Form for any committee: <a href="{% url 'statisticscore:content_all' session.pk %}">{% url 'statisticscore:content_all' session.pk %}</a></h5>
                {% elif session.session_statistics == 'C' %}
                    <h5>Content Form for any committee: <a href="{% url 'statisticscore:content_all' session.pk %}">{% url 'statisticscore:content_all' session.pk %}</a></h5>
                {% elif session.session_statistics == 'S' %}
                    <h5>Statistics Form for any committee: <a href="{% url 'statisticscore:point_all' session.pk %}">{% url 'statisticscore:point_all' session.pk %}</a></h5>
                {% endif %}
                {% if session.voting_enabled %}
                    <h5>Voting Form for any committee: <a href="{% url 'statisticscore:vote_all' session.pk %}">{% url 'statisticscore:vote_all' session.pk %}</a></h5>
                {% endif %}
            {% else %}
                <h3>No Committees Yet!</h3>
                <h4>You can make some here: <a href="{% url 'statisticscore:create_committee' session.pk %}">{% url 'statisticscore:create_committee' session.pk %}</a></h4>
            {% endif %}
        </div>
    </div>
    <style>
        tbody tr td {
            font-size: 15px;
        }
    </style>

{% endblock %} {% block footer_scripts %} {% endblock %}