eypstats/urls.py
from django.conf import settings
from django.urls import include, re_path
from statisticscore.admin import admin_site

urlpatterns = [
    re_path(r'^', include('statisticscore.urls')),
    re_path(r'^admin/', admin_site.urls),
]

handler404 = 'statisticscore.views.public_views.handler404'
handler500 = 'statisticscore.views.public_views.handler500'

statisticscore/urls.py
from django.urls import re_path
from django.conf.urls.static import static
from django.conf import settings

from statisticscore.views import *
from statisticscore.url_patterns.api import api_urls
from statisticscore.url_patterns.session import session_urls

# The URLs are quite important to the GA Stats system, as there's a custom API and system for accessing various forms
# Sessions, Debates, Point Submit and Vote Submit pages are accessed using the id's of the session/committee.
# The special ones are the api urls that the debate and session pages use for the live reloading to function,
# they're linked to custom views that output some pretty JSON output.

app_name = 'statisticscore'

urlpatterns = [
    re_path(r'^$', home, name='home'),
    re_path(r'^login/$', ga_login, name='login'),
    re_path(r'^logout/$', ga_logout, name='logout'),
    re_path(r'^get_started/$', get_started, name='get_started'),
    re_path(r'^changelog/$', changelog, name='changelog'),
    re_path(r'^create_session/$', create_session, name='create_session'),
    re_path(r'^highscores/$', high_scores, name='high_scores'),
    re_path(r'^topics/$', FilteredTopicsListView.as_view(), name='topics'),
    # path('topics/<int:pk>/edit', TopicUpdate.as_view(), name='update_topic'),
    # path('topics/<int:pk>/', TopicDetail.as_view(), name='topic_detail'),
    re_path(r'^overview/(?P<session_id>[0-9]+)/$', overview, name='overview'),
    re_path(r'^edit/(?P<session_id>[0-9]+)/$', edit, name='edit'),
    re_path(r'^committees/(?P<session_id>[0-9]+)/$', create_committee, name='create_committee'),
    re_path(r'^manage/(?P<session_id>[0-9]+)/$', manage, name='manage'),
    re_path(r'^gender/(?P<session_id>[0-9]+)/$', gender, name='gender'),
    re_path(r'^runningorder/(?P<session_id>[0-9]+)/$', runningorder, name='runningorder'),
]

urlpatterns += api_urls
urlpatterns += session_urls

if settings.IS_DEVELOPMENT:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

statisticscore/forms/point.py
from django import forms


class PointForm(forms.Form):
    #The point form needs to be fed with special data, in the form of an array of subtopics.
    #To do this, we change the definition of the form to accept an extra argument, the array of subtopics.
    def __init__(self, subtopic_choices, *args, **kwargs):
        super(PointForm, self).__init__(*args, **kwargs)
        self.fields['subtopics'].choices = subtopic_choices

    #This is setting up the point types in the same way as they are set up in the models file
    POINT = 'P'
    DIRECT_RESPONSE = 'DR'
    POINT_TYPES = (
        (POINT, 'Point'),
        (DIRECT_RESPONSE, 'Direct Response'),
    )

    #These are the other arguments that the point form needs for a successfully submitted point.
    #Note that the choices of the point_type is the previously defined point types and that
    #the choices for the subtopics needs to be set up, but empty.
    session = forms.CharField(max_length=100, required=True)
    committee = forms.CharField(max_length=8, required=True)
    debate = forms.CharField(max_length=8, required=True)
    round_no = forms.IntegerField(min_value=0, required=True)
    point_type = forms.ChoiceField(choices=POINT_TYPES, required=True)
    subtopics = forms.MultipleChoiceField(choices=(), required=True)


class PointEditForm(forms.Form):
    #This is setting up the point types in the same way as they are set up in the models file
    POINT = 'P'
    DIRECT_RESPONSE = 'DR'
    POINT_TYPES = (
        (POINT, 'Point'),
        (DIRECT_RESPONSE, 'Direct Response'),
    )

    #These are the other arguments that the point form needs for a successfully submitted point.
    #Note that the choices of the point_type is the previously defined point types and that
    #the choices for the subtopics needs to be set up, but empty.
    pk = forms.IntegerField(min_value=0, required=True)
    session = forms.IntegerField(min_value=0, required=True)
    committee = forms.CharField(max_length=8, required=True)
    debate = forms.CharField(max_length=8, required=True)
    round_no = forms.IntegerField(min_value=0, required=True)
    point_type = forms.ChoiceField(choices=POINT_TYPES, required=True)

statisticscore/forms/vote.py
from django import forms


class VoteForm(forms.Form):
    #The vote form is simpler, as there are no custom definitions required, just plain data.
    session = forms.CharField(max_length=100, required=True)
    committee = forms.CharField(max_length=8, required=True)
    debate = forms.CharField(max_length=8, required=True)
    in_favour = forms.IntegerField(min_value=0, required=True)
    against = forms.IntegerField(min_value=0, required=True)
    abstentions = forms.IntegerField(min_value=0, required=True)
    absent = forms.IntegerField(min_value=0, required=True)

class VoteEditForm(forms.Form):
    #The vote form is simpler, as there are no custom definitions required, just plain data.
    pk = forms.IntegerField(min_value=0, required=True)
    session = forms.IntegerField(min_value=0, required=True)
    committee = forms.CharField(max_length=8, required=True)
    debate = forms.CharField(max_length=8, required=True)
    in_favour = forms.IntegerField(min_value=0, required=True)
    against = forms.IntegerField(min_value=0, required=True)
    abstentions = forms.IntegerField(min_value=0, required=True)
    absent = forms.IntegerField(min_value=0, required=True)

statistics/views.py
import time
import json

from datetime import date
from datetime import datetime
from time import strftime

from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.models import User
from django.contrib.auth.models import Group
from django.contrib.auth import get_user_model, authenticate, login, logout
from django.contrib import messages

#Importing all models for statistics.
from .models import Session, Committee, Point, ContentPoint, Vote, SubTopic, ActiveDebate, ActiveRound

#Importing the forms too.
from .forms import SessionForm,  SessionEditForm, PointForm, VoteForm, ContentForm, JointForm, ActiveDebateForm, ActiveRoundForm, LoginForm

def home(request):
    #All the home page needs is a list of all sessions ordered by the start date. We create the list, then the context and finally render the template.
    latest_sessions_list = Session.objects.filter(session_is_visible=True).order_by('-session_start_date')[:20]
    context = {'latest_sessions_list': latest_sessions_list}
    return render(request, 'statistics/home.html', context)

def ga_login(request):
# This view is shown, when a user tries to view the submit form, but isn't logged in. After they log in, they'll be taken to /submit/.
    form = LoginForm(request.POST or None)

    if form.is_valid():
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        print username, password

        user = authenticate(username=username,
                            password=password)

        if user is not None:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect('/')
            else:
                return HttpResponseRedirect('/login')
        else:
            return HttpResponseRedirect('/login')

    template = 'statistics/login.html'
    context = {'form': form}
    return render(request, template, context)


def ga_logout(request):
    # If the user visits /logout/ he will be logged out.

    logout(request)
    return HttpResponseRedirect('/')


def create_session(request):
    #If the user is trying to create a session
    if request.method == 'POST':
        print request.POST
        #Fill an instance of a SessionForm with the request data.
        form = SessionForm(request.POST)

        if form.is_valid():
            print 'is valid'
            #We need to set up time varaibles for the start and end of sessions.
            #We do this by creating date objects and combining the date objects with time midnight
            t_start = form.cleaned_data['start_date']
            t_end = form.cleaned_data['end_date']
            start_date = datetime.combine(t_start, datetime.min.time())
            end_date = datetime.combine(t_end, datetime.min.time())

            #We need to turn the voting 'True' and 'False' strings into actual booleans.
            if form.cleaned_data['voting'] == 'True':
                voting = True
            else:
                voting = False

            #Creating a lowercase string with no spaces from the session name to use for usernames
            name = ''.join(form.cleaned_data['name'].split()).lower()

            #Creating the Admin user
            admin_user = User.objects.create_user(username = name + '_admin',
                email = form.cleaned_data['email'],
                password = form.cleaned_data['admin_password'])

            #Adding the admin user to the admin group.
            admin_group = Group.objects.get(name='SessionAdmin')
            admin_group.user_set.add(admin_user)

            #Creating the Submit user
            submit_user = User.objects.create_user(username = name,
                email = form.cleaned_data['email'],
                password = form.cleaned_data['submit_password'])

            #Adding the Submit user to the submit group.
            submit_group = Group.objects.get(name='SessionSubmit')
            submit_group.user_set.add(submit_user)

            #We need to create a session, active debate and active round. We also need to create 2 new users for the session.
            session = Session(session_name = form.cleaned_data['name'],
                session_description = form.cleaned_data['description'],
                session_picture = form.cleaned_data['picture'],
                session_email = form.cleaned_data['email'],
                session_country = form.cleaned_data['country'],
                session_start_date = start_date,
                session_end_date = end_date,
                session_statistics = form.cleaned_data['statistics'],
                session_color = form.cleaned_data['color'],
                session_rounds_enabled = True,
                session_subtopics_enabled = True,
                session_is_visible = False,
                session_voting_enabled = voting,
                session_max_rounds = form.cleaned_data['max_rounds'],
                session_admin_user = admin_user,
                session_submission_user = submit_user,
                )
            session.save()
            active_debate = ActiveDebate(session = session, active_debate = '')
            active_debate.save()
            active_round = ActiveRound(session = session, active_round = 1)
            active_round.save()

            #Once we've done all that, lets say thanks for all that hard work.
            return HttpResponseRedirect('/welcome/' + str(session.pk) + '/')
        else:
            print 'Wasnt valid'
            print form.errors
    else:
        #Otherwise, create a nice new form for the user.
        form = SessionForm()

    context = {'form': form}
    return render(request, 'statistics/session_create.html', context)

def welcome(request, session_id):
    session = Session.objects.get(pk=session_id)
    committees = Committee.objects.filter(session=session).order_by('committee_name')
    context = {'session': session, 'committees': committees}
    return render(request, 'statistics/welcome.html', context)

def edit(request, session_id):
    s = Session.objects.get(pk=session_id)
    # If the User is trying to edit the session
    if request.method == 'POST':
        #Fill an instance of the form with the request data.
        form = SessionEditForm(request.POST)
        #Check if the created form is a valid form.
        if form.is_valid():
            print 'is valid'
            #We need to set up time varaibles for the start and end of sessions.
            #We do this by creating date objects and combining the date objects with time midnight
            t_start = form.cleaned_data['start_date']
            t_end = form.cleaned_data['end_date']
            start_date = datetime.combine(t_start, datetime.min.time())
            end_date = datetime.combine(t_end, datetime.min.time())

            s.session_name = form.cleaned_data['name']
            s.session_description = form.cleaned_data['description']
            s.session_picture = form.cleaned_data['picture']
            s.session_email = form.cleaned_data['email']
            s.session_country = form.cleaned_data['country']
            s.session_start_date = start_date
            s.session_end_date = end_date
            s.session_statistics = form.cleaned_data['statistics']
            s.session_voting_enabled = form.cleaned_data['voting']
            s.session_max_rounds = form.cleaned_data['max_rounds']
            s.session_color = form.cleaned_data['color']
            s.session_is_visible = form.cleaned_data['is_visible']
            #Save the newly edited session
            s.save()

            messages.add_message(request, messages.SUCCESS, 'Session Updated')

    else:
        form = SessionEditForm({'name': s.session_name,
            'description': s.session_description,
            'email': s.session_email,
            'country': s.session_country,
            'picture': s.session_picture,
            'start_date': s.session_start_date.strftime("%Y-%m-%d"),
            'end_date': s.session_end_date.strftime("%Y-%m-%d"),
            'statistics': s.session_statistics,
            'voting': s.session_voting_enabled,
            'max_rounds': s.session_max_rounds,
            'color': s.session_color,
            'is_visible': s.session_is_visible})

    context = {'session': s, 'form': form}
    return render(request, 'statistics/session_edit.html', context)


def add(request, session_id):
    pass

def session(request, session_id):
    #The Session page uses static content and content that is constantly updated, the satic content is loaded with the view
    #and the updating content updates with the session api, defined further down.

    #The static data here is simply a list of the available committees (we can assume those don't change during live statistics)
    #and the name and data of the session itself.
    session_committee_list = Committee.objects.filter(session__id=session_id)[:30]
    session = Session.objects.get(pk=session_id)
    voting_enabled = session.session_voting_enabled
    context = {'session_committee_list': session_committee_list, 'session_id': session_id, 'session': session, 'voting_enabled': voting_enabled}
    return render(request, 'statistics/session.html', context)

def debate(request, session_id, committee_id):
    #Same for debates as for sessions, the only static content is the name and data of the committee and the session.
    #The rest of the point/voting data comes through the api that can constantly be updated.
    c = Committee.objects.get(pk=committee_id)
    s = Session.objects.get(pk=session_id)
    #The statistics_type will let us render different templates based on the statistics selected by the user.
    statistics_type = s.session_statistics
    print statistics_type

    #The voting enabled option lets us change the html content and js so that the voting is not displayed.
    voting_enabled = s.session_voting_enabled

statistics/templates/statistics/point.html
{% extends 'statistics/base.html' %}

{% load staticfiles %}

{% block page_title %}Submit Point: {{ committee.committee_name }}{% endblock %}

{% block content %}
<h1 style="text-align: center">Submit point from {{ committee.committee_name }} on {{ debate }}</h1>
<br>
<form class="form-horizontal" role="form" action="{% url 'statistics:point' session.id committee.id %}" method="post">
  {% csrf_token %}
  <div class="form-group">
    <label class="control-label col-sm-2" for="{{ form.session.id_for_label }}">Session:</label>
    <div class="col-sm-10">
      {{ form.session.errors }}
      <input type="text" class="form-control" name="{{ form.session.html_name }}" id="{{ form.session.id_for_label }}" maxlength=100 value="{{ form.session.value }}" readonly>
    </div>
  </div>
  <div class="form-group">
    <label class="control-label col-sm-2" for="{{ form.committee.id_for_label }}">Commitee:</label>
    <div class="col-sm-10">
      {{ form.committee.errors }}
      <input type="text" class="form-control" name="{{ form.committee.html_name }}" id="{{ form.committee.id_for_label }}" maxlength=7 value="{{ form.committee.value }}" readonly>
    </div>
  </div>
  <div class="form-group">
    <label class="control-label col-sm-2" for="{{ form.debate.id_for_label }}">Debate:</label>
    <div class="col-sm-10">
      {{ form.debate.errors }}
      <input type="text" class="form-control" name="{{ form.debate.html_name }}" id="{{ form.debate.id_for_label }}" value="{{ form.debate.value }}" readonly>
    </div>
  </div>
  <div class="form-group">
    <label class="control-label col-sm-2" for="{{ form.round_no.id_for_label }}">Round Number:</label>
    <div class="col-sm-10">
      {{ form.round_no.errors }}
      <input type="text" class="form-control" name="{{ form.round_no.html_name }}" id="{{ form.round_no.id_for_label }}" value="{{ form.round_no.value }}" readonly>
    </div>
  </div>
  <div class="form-group">
    <label class="control-label col-sm-2" for="{{ form.point_type.id_for_label }}">Point Type:</label>
    <div class="col-sm-10">
      {{ form.point_type.errors }}
      <select class="form-control" name="{{ form.point_type.html_name }}" id="{{ form.point_type.id_for_label }}">
        {% for id,text in form.fields.point_type.choices  %}
        <option value="{{ id }}" >{{ text }}</option>
        {% endfor %}
      </select>
    </div>
  </div>
  <div class="form-group">
    <label class="control-label col-sm-2" for="{{ form.subtopics.id_for_label }}">Subtopics Addressed:</label>
    <div class="col-sm-10">
      {{ form.subtopics.errors }}
      <select multiple class="form-control" name="{{ form.subtopics.html_name }}" id="{{ form.subtopics.id_for_label }}">
        {% for id,text in form.fields.subtopics.choices  %}
        <option value="{{ id }}">{{ text }}</option>
        {% endfor %}
      </select>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <button type="submit" class="btn btn-default">Submit</button>
    </div>
  </div>
</form>
{% endblock %}

{% block footer_scripts %}
{% endblock %}

statistics/templates/statistics/vote.html
{% extends 'statistics/base.html' %}

{% load staticfiles %}

{% block page_title %}Vote: {{ committee.committee_name }}{% endblock %}

{% block content %}
<h1 style="text-align: center">Voting for {{ committee.committee_name }} on {{ debate }}</h1>
<br>
<form class="form-horizontal" role="form" action="{% url 'statistics:vote' session.id committee.id %}" method="post">
  {% csrf_token %}
  <div class="form-group">
    <label class="control-label col-sm-2" for="{{ form.session.id_for_label }}">Session:</label>
    <div class="col-sm-10">
      {{ form.session.errors }}
      <input type="text" class="form-control" name="{{ form.session.html_name }}" id="{{ form.session.id_for_label }}" maxlength=100 value="{{ form.session.value }}" readonly>
    </div>
  </div>
  <div class="form-group">
    <label class="control-label col-sm-2" for="{{ form.committee.id_for_label }}">Commitee:</label>
    <div class="col-sm-10">
      {{ form.committee.errors }}
      <input type="text" class="form-control" name="{{ form.committee.html_name }}" id="{{ form.committee.id_for_label }}" maxlength=7 value="{{ form.committee.value }}" readonly>
    </div>
  </div>
  <div class="form-group">
    <label class="control-label col-sm-2" for="{{ form.debate.id_for_label }}">Debate:</label>
    <div class="col-sm-10">
      {{ form.debate.errors }}
      <input type="text" class="form-control" name="{{ form.debate.html_name }}" id="{{ form.debate.id_for_label }}" value="{{ form.debate.value }}" readonly>
    </div>
  </div>
  <div class="form-group">
    <label class="control-label col-sm-2" for="{{ form.in_favour.id_for_label }}">Votes In Favour:</label>
    <div class="col-sm-10">
      {{ form.in_favour.errors }}
      <input type="number" min="0" max="50" class="form-control" name="{{ form.in_favour.html_name }}" id="{{ form.in_favour.id_for_label }}" value="{{ form.in_favour.value }}">
    </div>
  </div>
  <div class="form-group">
    <label class="control-label col-sm-2" for="{{ form.against.id_for_label }}">Votes Against:</label>
    <div class="col-sm-10">
      {{ form.against.errors }}
      <input type="number" min="0" max="50" class="form-control" name="{{ form.against.html_name }}" id="{{ form.against.id_for_label }}" value="{{ form.against.value }}">
    </div>
  </div>
  <div class="form-group">
    <label class="control-label col-sm-2" for="{{ form.abstentions.id_for_label }}">Abstentions:</label>
    <div class="col-sm-10">
      {{ form.abstentions.errors }}
      <input type="number" min="0" max="50" class="form-control" name="{{ form.abstentions.html_name }}" id="{{ form.abstentions.id_for_label }}" value="{{ form.abstentions.value }}">
    </div>
  </div>
  <div class="form-group">
    <label class="control-label col-sm-2" for="{{ form.absent.id_for_label }}">Absent:</label>
    <div class="col-sm-10">
      {{ form.absent.errors }}
      <input type="number" min="0" max="50" class="form-control" name="{{ form.absent.html_name }}" id="{{ form.absent.id_for_label }}" value="{{ form.absent.value }}">
    </div>
  </div>
  <div class="form-group">
    <label class="control-label col-sm-2" >Total Votes:</label>
    <div class="col-sm-10">
      <h5 id="total"><h5>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <button type="submit" class="btn btn-default">Submit</button>
    </div>
  </div>
</form>
{% endblock %}

{% block footer_scripts %}
<script  type="text/javascript" src="{% static 'statistics/js/vote_form.js' %}"></script>
{% endblock %}

statistics/templates/statistics/welcome.html
{% extends 'statistics/base.html' %}

{% load staticfiles %}

{% block page_title %}Welcome - {{ session.session_name }}{% endblock %}

{% block jumbotron %}
    <div class="welcome-jumbo jumbotron">
        <div class="container">
            <h1>Welcome to GA Statistics, {{ session.session_name }}</h1>
            <p>Congratulations on creating your GA Statistics Session, there are a few more things you need to do before you're ready to go.</p>
        </div><!--/.container -->
    </div><!--/.jumbotron -->
{% endblock %}

{% block content %}
    <div class="container">
    {% if session.session_is_visible %}
    {% else %}
        <div class="alert alert-dismissable alert-warning">
            <button type="button" class="close" data-dismiss="alert">×</button>
            Your session isn't visible to the public yet, when you're ready to activate it, do so here: <a href="{% url 'statistics:edit' session.pk %}">{% url 'statistics:edit' session.pk %}</a>
        </div>
    {% endif %}
    <div class="alert alert-dismissable alert-info">
        <button type="button" class="close" data-dismiss="alert">×</button>
        This is really important stuff to know, but don't worry, you can always come back here with this url: <a href="{% url 'statistics:welcome' session.pk %}">{% url 'statistics:welcome' session.pk %}</a>
    </div>

    <div class="panel panel-primary">
        <div class="panel-heading">
            <h3 class="panel-title">Usernames</h3>
        </div>
        <div class="panel-body">
            <h4>Your Admin Username is <b>{{ session.session_admin_user }}</b><h4>
                <h5>The Admin Password that you entered when you made the session.</h5>
                <br>
                <h4>Your Submission Username is <b>{{ session.session_submission_user }}</b></h4>
                <h5>The Submission Password that you entered when you made the session.</h5>
        </div>
    </div>
    <div class="panel panel-primary">
        <div class="panel-heading">
            <h3 class="panel-title">{{ session.session_name }} Links</h3>
        </div>
        <div class="panel-body">
            <h2>Your Session ID is <b>{{ session.pk }}</b></h2>
            <p>You can use your session ID for all kinds of things (some only if you're logged in as an admin).</p>

            <h3>You can add your committees:</h3>
            <h4><a href="{% url 'statistics:add' session.pk %}">{% url 'statistics:add' session.pk %}</a> - This is where you add all your committees and subtopics.</h3>

                <h3>You can edit the session you just made:</h3>
                <h4><a href="{% url 'statistics:edit' session.pk %}">{% url 'statistics:edit' session.pk %}</a> - This is where you can change things like the maximum amount of rounds you'll have.</h3>

                    <h3>You can manage your session:</h3>
                    <h4><a href="{% url 'statistics:manage' session.pk %}">{% url 'statistics:manage' session.pk %}</a> - This is where you let the system know which debate and round is going on at the moment.</h3>
                        <p>It's also where you can edit recent points, contentpoints and votes</p>

                        {% if session.session_gender_enabled %}
                            <h3>You can track the equality of your session here:</h3>
                            <h4><a href="{% url 'statistics:gender' session.pk %}">{% url 'statistics:gender' session.pk %}</a> - This is where you add "Gender Points" which only show up in the admin.</h3>
                            <p>It's also where you remove accedental gender points</p>
                        {% endif %}

        </div>
    </div>
    <div class="panel panel-primary">
        <div class="panel-heading">
            <h3 class="panel-title">Committees</h3>
        </div>
        <div class="panel-body">
            {% if committees %}
                <table class="table table-striped table-hover ">
                    <thead>
                    <tr>
                        <th>ID</th>
                        <th>Name</th>
                        <th>Debate URL</th>
                        {% if session.session_statistics == 'JF' %}
                            <th>Joint Form URL</th>
                        {% elif session.session_statistics == 'SF' %}
                            <th>Statistics Form URL</th>
                            <th>Content Form URL</th>
                        {% elif session.session_statistics == 'C' %}
                            <th>Content Form URL</th>
                        {% elif session.session_statistics == 'S' %}
                            <th>Statistics Form URL</th>
                        {% endif %}
                        {% if session.session_voting_enabled %}
                            <th>Voting URL<th>
                        {% endif %}
                    </tr>
                    </thead>
                    <tbody>
                    {% for committee in committees %}
                        <tr>
                            <td>{{ committee.pk }}</td>
                            <td>{{ committee.committee_name }}
                            <td><a href="{% url 'statistics:debate' session.pk committee.pk %}">{% url 'statistics:debate' session.pk committee.pk %}</a></td>
                            {% if session.session_statistics == 'JF' %}
                                <td><a href="{% url 'statistics:joint' session.pk committee.pk %}">{% url 'statistics:joint' session.pk committee.pk %}</a></td>
                            {% elif session.session_statistics == 'SF' %}
                                <td><a href="{% url 'statistics:point' session.pk committee.pk %}">{% url 'statistics:point' session.pk committee.pk %}</a></td>
                                <td><a href="{% url 'statistics:content' session.pk committee.pk %}">{% url 'statistics:content' session.pk committee.pk %}</a></td>
                            {% elif session.session_statistics == 'C' %}
                                <td><a href="{% url 'statistics:content' session.pk committee.pk %}">{% url 'statistics:content' session.pk committee.pk %}</a></td>
                            {% elif session.session_statistics == 'S' %}
                                <td><a href="{% url 'statistics:point' session.pk committee.pk %}">{% url 'statistics:point' session.pk committee.pk %}</a></td>
                            {% endif %}
                            {% if session.session_voting_enabled %}
                                <td><a href="{% url 'statistics:vote' session.pk committee.pk %}">{% url 'statistics:vote' session.pk committee.pk %}</a><td>
                            {% endif %}
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
                <p>We highly recommend using the links above and giving them to your chairs/journos/orgas who will fill in data for one committee each. Using those links minimises the probability of something going wrong = less work for you.
                    However, if you only have one small group of people filling in all statistics, there are some special forms that can make their lives a little easier:</p>
                {% if session.session_statistics == 'JF' %}
                    <h5>Joint Form for any committee: <a href="{% url 'statistics:joint_all' session.pk %}">{% url 'statistics:joint_all' session.pk %}</a></h5>
                {% elif session.session_statistics == 'SF' %}
                    <h5>Statistics Form for any committee: <a href="{% url 'statistics:point_all' session.pk %}">{% url 'statistics:point_all' session.pk %}</a></h5>
                    <h5>Content Form for any committee: <a href="{% url 'statistics:content_all' session.pk %}">{% url 'statistics:content_all' session.pk %}</a></h5>
                {% elif session.session_statistics == 'C' %}
                    <h5>Content Form for any committee: <a href="{% url 'statistics:content_all' session.pk %}">{% url 'statistics:content_all' session.pk %}</a></h5>
                {% elif session.session_statistics == 'S' %}
                    <h5>Statistics Form for any committee: <a href="{% url 'statistics:point_all' session.pk %}">{% url 'statistics:point_all' session.pk %}</a></h5>
                {% endif %}
                {% if session.session_voting_enabled %}
                    <h5>Voting Form for any committee: <a href="{% url 'statistics:vote_all' session.pk %}">{% url 'statistics:vote_all' session.pk %}</a></h5>
                {% endif %}
            {% else %}
                <h3>No Committees Yet!</h3>
                <h4>You can make some here: <a href="{% url 'statistics:add' session.pk %}">{% url 'statistics:add' session.pk %}</a></h4>
            {% endif %}
        </div>
    </div>
    <style>
        tbody tr td {
            font-size: 15px;
        }
    </style>

{% endblock %} {% block footer_scripts %} {% endblock %}